---
- hosts: localhost
  connection: local

  vars_files:
    - "{{ manuscript | default('./manuscripts/default-mac.yml')}}"

  tasks:

    - name: File manipulations
      file:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'file') | list }}"

    - name: Git repos
      git:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'git') | list }}"

    - name: Setup brew taps
      homebrew_tap:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'homebrew_tap') | list }}"

    - name: Install kegs with brew
      homebrew:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'homebrew') | list }}"

    - name: Install casks with brew-cask
      homebrew_cask:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'homebrew_cask') | list }}"

    - name: Install Ruby gems
      gem:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'gem') | list }}"

    - name: Shell executions
      shell: "{{ item.shell }}"
      args:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'shell') | list }}"

    - name: Command executions
      command: "{{ item.command }}"
      args:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'command') | list }}"

    - name: Configure git
      git_config:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'git_config') | list }}"

    - name: Configuration file manipulations
      lineinfile:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'lineinfile') | list }}"
